apiVersion: v1
kind: Service
metadata:
  name: campus-maintenance-service
spec:
  selector:
    app: campus-maintenance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer